events {
    worker_connections 1024;
}

http {
	server {
	    listen 8000;
            listen [::]:8000;
	    
	    location / {
		auth_basic           "ataka";
		auth_basic_user_file /.htpasswd;
		proxy_pass http://api:8000;
	    }
	}
}
